ARG VERSION

FROM bitnami/minideb:stretch
RUN install_packages ca-certificates curl git
RUN curl https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz | tar -xzf - -C /usr/local
ENV PATH="/usr/local/go/bin:$PATH" CGO_ENABLED=0
RUN go get -u github.com/golang/glog && go get -u github.com/kubeapps/kubeapps/cmd/tiller-proxy
RUN go build -a -installsuffix cgo -ldflags "-X main.version=$VERSION" github.com/kubeapps/kubeapps/cmd/tiller-proxy

EXPOSE 80
CMD ["/tiller-proxy"]
